<div class="page-header">
    <h1>Horizontal Form 2</h1>
</div>
<?php
$formDisplayConfig  = array(
    'fullName'      => array(
        'sizeClass'     => 'span4',
    ),
    'password'      => array(
        'sizeClass'     => 'span3',
    ),
    'notes'         => array(
        'sizeClass'     => 'span4',
        'rows'          => 5,
    ),
    'rateUs'        => array(
        'inline'        => true,
    ),
    'seenMovies'    => array(
        'inline'        => true,
    ),
);


$formType   = \DluTwBootstrap\Form\Util::FORM_TYPE_HORIZONTAL;
$form = $this->form;
/* @var $form \DluTwBootstrap\Demo\Form\BlockForm */
$form->prepare();
$inputFilter    = $form->getInputFilter();
//$form->setAttribute('action', $this->url('form'));
?>

<?php //echo $this->formTwb()->openTag($form, $formType); ?>
<?php //echo $this->formFieldsetTwb()->openTag($form->get('fsMainInfo'), $formType); ?>
<?php //echo $this->formFieldsetTwb()->content($form->get('fsMainInfo'), $formType, $inputFilter, array('fullName' => array('sizeClass' => 'span3'))); ?>
<?php //echo $this->formFieldsetTwb()->closeTag(); ?>
<?php //echo $this->formFieldsetTwb($form->get('fsMainInfo'), $formType, $inputFilter, array('fullName' => array('sizeClass' => 'span5'))); ?>
<?php //echo $this->formTwb()->actions($form, $formType); ?>
<?php //echo $this->formTwb()->closeTag(); ?>

<?php echo $this->formTwb($form, $formType, $formDisplayConfig); ?>