<div class="page-header">
    <h1>Horizontal Form 2</h1>
</div>
<?php
$formType   = \DluTwBootstrap\Form\Util::FORM_TYPE_HORIZONTAL;
$form = $this->form;
/* @var $form \DluTwBootstrap\Demo\Form\BlockForm */
$form->setAttribute('class', 'form-horizontal');
//$form->setAttribute('action', $this->url('form'));
$inputFilter    = $form->getInputFilter();
echo $this->form()->openTag($form);
?>
<fieldset>
    <?php echo $this->formTwb()->formElements($form, $formType); ?>
    <?php echo $this->formTwb()->formActions($form, $formType); ?>
</fieldset>
<?php echo $this->form()->closeTag(); ?>