<div class="page-header">
    <h1>Inline Form</h1>
</div>
<?php
$formDisplayConfig  = array(
    'text'      => array(
        'sizeClass'     => 'span1',
    ),
    'password'      => array(
        'sizeClass'     => 'span1',
    ),
    'multiCheckbox'    => array(
        'inline'        => true,
    ),
    'select'      => array(
        'sizeClass'     => 'span1',
    ),
    'textAp'      => array(
        'sizeClass'     => 'span1',
    ),
);
$formType   = \DluTwBootstrap\Form\Util::FORM_TYPE_INLINE;
$form = $this->form;
/* @var $form \DluTwBootstrap\Demo\Form\InlineForm */
$form->prepare();
//$form->setAttribute('action', $this->url('form'));
?>

<?php echo $this->formTwb($form, $formType, $formDisplayConfig); ?>