<div class="page-header">
    <h1>Horizontal Form - Manually rendered elements</h1>
</div>
<?php
$formType   = \DluTwBootstrap\Form\Util::FORM_TYPE_HORIZONTAL;
$form = $this->form;
/* @var $form \DluTwBootstrap\Demo\Form\BlockForm */
$form->prepare();
//$form->setAttribute('action', $this->url('form'));
$inputFilter    = $form->getInputFilter();
echo $this->formTwb()->openTag($form, $formType);
?>
    <!-- Hidden -->
    <?php //echo $this->formInputTwb($form->get('hiddenField')); ?>
    <?php //echo $this->formElementTwb($form->get('hiddenField')); ?>
    <?php echo $this->formElementFullTwb($form->get('hiddenField'), $formType); ?>

    <?php echo $this->formFieldsetTwb()->openTag($form->get('fsMainInfo'), $formType); ?>
    <!-- Text -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('fullName')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('fullName'), null, null, $formType, $inputFilter->get('fullName')); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('fullName'), 'span3'); ?>
            <?php //echo $this->formElementTwb($form->get('fullName'), array('sizeClass' => 'span4')); ?>
            <?php //echo $this->formElementErrorsTwb($form->get('fullName')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('fsMainInfo')->get('fullName'),
                                         $formType,
                                         $inputFilter->get('fullName'),
                                         array('sizeClass' => 'span4')); ?>

    <!-- Password -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('password')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('password'), null, null, $formType, $inputFilter->get('password')); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('password'), 'span3'); ?>
            <?php //echo $this->formElementTwb($form->get('password'), array('sizeClass' => 'span3')); ?>
            <?php //echo $this->formElementErrorsTwb($form->get('password')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('fsMainInfo')->get('password'),
                                         $formType,
                                         $inputFilter->get('password'),
                                         array('sizeClass' => 'span3')); ?>

    <!-- Textarea -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('notes')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('notes'), null, null, $formType, $inputFilter->get('notes')); ?>
        <div class="controls">
            <?php //echo $this->formTextareaTwb($form->get('notes'), 'span4', 8); ?>
            <?php //echo $this->formElementTwb($form->get('notes'), array('sizeClass' => 'span4', 'rows' => 4)); ?>
            <?php //echo $this->formElementErrorsTwb($form->get('notes')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('fsMainInfo')->get('notes'),
                                         $formType,
                                         $inputFilter->get('notes'),
                                         array('sizeClass' => 'span4', 'rows' => 3)); ?>

    <?php echo $this->formFieldsetTwb()->closeTag(); ?>

    <!-- Checkbox -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('pastaEater')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('pastaEater'), null, null, $formType, $inputFilter->get('pastaEater')); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('pastaEater')); ?>
            <?php //echo $this->formElementTwb($form->get('pastaEater')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('pastaEater'),
                                         $formType,
                                         $inputFilter->get('pastaEater')); ?>


<fieldset>
    <?php echo $this->formTwb()->fieldsetLegend('Second section'); ?>
    <!-- Radio -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('level')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('level'), null, null, $formType, $inputFilter->get('level')); ?>
        <div class="controls">
            <?php //echo $this->formRadioTwb($form->get('level')); ?>
            <?php //echo $this->formElementTwb($form->get('level')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('level'),
                                         $formType,
                                         $inputFilter->get('level')); ?>

    <!-- Radio inline -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('rateUs')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('rateUs'), null, null, $formType, $inputFilter->get('rateUs')); ?>
        <div class="controls">
            <?php //echo $this->formRadioTwb($form->get('rateUs'), true); ?>
            <?php //echo $this->formElementTwb($form->get('rateUs'), array('inline' => true)); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('rateUs'),
                                         $formType,
                                         $inputFilter->get('rateUs'),
                                         array('inline' => true)); ?>

    <!-- MultiCheckbox -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('settings')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('settings'), null, null, $formType, $inputFilter->get('settings')); ?>
        <div class="controls">
            <?php //echo $this->formMultiCheckboxTwb($form->get('settings')); ?>
            <?php //echo $this->formElementTwb($form->get('settings')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('settings'),
                                         $formType,
                                         $inputFilter->get('settings')); ?>

    <!-- MultiCheckbox inline -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('seenMovies')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('seenMovies'), null, null, $formType, $inputFilter->get('seenMovies')); ?>
        <div class="controls">
            <?php //echo $this->formMultiCheckboxTwb($form->get('seenMovies'), true); ?>
            <?php //echo $this->formElementTwb($form->get('seenMovies'), array('inline' => true)); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('seenMovies'),
                                         $formType,
                                         $inputFilter->get('seenMovies'),
                                         array('inline' => true)); ?>

    <!-- Select -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('car')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('car'), null, null, $formType, $inputFilter->get('car')); ?>
        <div class="controls">
            <?php //echo $this->formSelectTwb($form->get('car'), 'span3'); ?>
            <?php //echo $this->formElementTwb($form->get('car'), array('sizeClass' => 'span3')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('car'),
                                         $formType,
                                         $inputFilter->get('car'),
                                         array('sizeClass' => 'span3')); ?>

    <!-- MultiSelect -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('pets')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('pets'), null, null, $formType, $inputFilter->get('pets')); ?>
        <div class="controls">
            <?php //echo $this->formSelectTwb($form->get('pets'), 'span4'); ?>
            <?php //echo $this->formElementTwb($form->get('pets'), array('sizeClass' => 'span4')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('pets'),
                                         $formType,
                                         $inputFilter->get('pets'),
                                         array('sizeClass' => 'span2')); ?>

    <!-- File -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('attachment')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('attachment'), null, null, $formType, $inputFilter->get('attachment')); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('attachment')); ?>
            <?php //echo $this->formElementTwb($form->get('attachment')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('attachment'),
                                         $formType,
                                         $inputFilter->get('attachment'),
                                         array('sizeClass' => 'span4')); ?>

    <!-- Text with append / prepend -->
    <!--
    <?php //echo $this->formControlGroupTwb()->openTag($form->get('salary')); ?>
        <?php //echo $this->formLabelMainTwb($form->get('salary'), null, null, $formType, $inputFilter->get('salary')); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('salary'), 'span5'); ?>
            <?php //echo $this->formElementTwb($form->get('salary'), array('sizeClass' => 'span3')); ?>
        </div>
    <?php //echo $this->formControlGroupTwb()->closeTag(); ?>
    -->
    <?php echo $this->formElementFullTwb($form->get('salary'),
                                         $formType,
                                         $inputFilter->get('salary'),
                                         array('sizeClass' => 'span3')); ?>

    <!-- CSRF -->
    <?php //echo $this->formElementTwb($form->get('csrf')); ?>
    <?php //echo $this->formElementErrorsTwb($form->get('csrf')); ?>
    <?php echo $this->formElementFullTwb($form->get('csrf'),
                                         $formType); ?>

    <!-- Form actions -->
    <!--
    <div class="form-actions">
        <?php //echo $this->formInputTwb($form->get('submitBtn')); ?>
        <?php //echo $this->formElementTwb($form->get('submitBtn')); ?>
        <?php //echo $this->formElementFullTwb($form->get('submitBtn'), $formType); ?>
        <?php //echo $this->formInputTwb($form->get('resetBtn')); ?>
        <?php //echo $this->formElementTwb($form->get('resetBtn')); ?>
        <?php //echo $this->formElementFullTwb($form->get('resetBtn'), $formType); ?>
        <?php //echo $this->formInputTwb($form->get('plainBtn')); ?>
        <?php //echo $this->formElementTwb($form->get('plainBtn')); ?>
        <?php //echo $this->formElementFullTwb($form->get('plainBtn'), $formType); ?>
    </div>
    -->
</fieldset>
<?php echo $this->formTwb()->actions($form, $formType); ?>
<?php echo $this->formTwb()->closeTag(); ?>