<div class="page-header">
    <h1>Horizontal Form</h1>
</div>
<div class="tabbable">
    <ul class="nav nav-tabs">
        <li class="active"><a href="#output" data-toggle="tab">Output</a></li>
        <li><a href="#formClass" data-toggle="tab">Form</a></li>
        <li><a href="#inputFilter" data-toggle="tab">Input filter</a></li>
        <li><a href="#viewScript" data-toggle="tab">View script</a></li>
    </ul>
    <div class="tab-content">
        <div class="tab-pane active" id="output">
            <?php echo $this->formOutput; ?>
        </div>
        <div class="tab-pane" id="formClass">
            <p>File: <code>&lt;module dir&gt;<?php echo $this->escape($this->formFile); ?></code></p>
            <pre class="prettyprint linenums">
<?php echo $this->escape($this->formSource); ?>
            </pre>
        </div>
        <div class="tab-pane" id="inputFilter">
            <p>File: <code>&lt;module dir&gt;<?php echo $this->escape($this->inputFilterFile); ?></code></p>
            <pre class="prettyprint linenums">
<?php echo $this->escape($this->inputFilterSource); ?>
            </pre>
        </div>
        <div class="tab-pane" id="viewScript">
            <p>File: <code>&lt;module dir&gt;<?php echo $this->escape($this->viewScriptFile); ?></code></p>
            <pre class="prettyprint linenums">
<?php echo $this->escape($this->viewScriptSource); ?>
            </pre>
        </div>
    </div>
</div>



