<div class="page-header">
    <h1>Horizontal Form</h1>
</div>
<?php
$formType   = \DluTwBootstrap\Form\Util::FORM_TYPE_HORIZONTAL;
$form = $this->form;
/* @var $form \DluTwBootstrap\Demo\Form\BlockForm */
$form->setAttribute('class', 'form-horizontal');
//$form->setAttribute('action', $this->url('form'));
echo $this->form()->openTag($form);
?>
<fieldset>
    <!-- Hidden -->
    <?php echo $this->formInputTwb($form->get('hiddenField')); ?>

    <!-- Text -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('fullName'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('fullName')); ?>
            <?php echo $this->formElementTwb($form->get('fullName')); ?>
        </div>
    </div>

    <!-- Password -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('password'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('password')); ?>
            <?php echo $this->formElementTwb($form->get('password')); ?>
        </div>
    </div>

    <!-- Textarea -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('notes'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formTextareaTwb($form->get('notes')); ?>
            <?php echo $this->formElementTwb($form->get('notes')); ?>
        </div>
    </div>

    <!-- Checkbox -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('pastaEater'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('pastaEater')); ?>
            <?php echo $this->formElementTwb($form->get('pastaEater')); ?>
        </div>
    </div>

    <!-- Radio -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('level'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formRadioTwb($form->get('level')); ?>
            <?php echo $this->formElementTwb($form->get('level')); ?>
        </div>
    </div>

    <!-- Radio inline -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('rateUs'), null, null, $formType); ?>
        <div class="controls">
            <?php echo $this->formRadioTwb($form->get('rateUs'), true); ?>
            <?php //echo $this->formElementTwb($form->get('rateUs'), true); ?>
        </div>
    </div>

    <!-- MultiCheckbox -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('settings'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formMultiCheckboxTwb($form->get('settings')); ?>
            <?php echo $this->formElementTwb($form->get('settings')); ?>
        </div>
    </div>

    <!-- MultiCheckbox inline -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('seenMovies'), null, null, $formType); ?>
        <div class="controls">
            <?php echo $this->formMultiCheckboxTwb($form->get('seenMovies'), true); ?>
            <?php //echo $this->formElementTwb($form->get('seenMovies'), true); ?>
        </div>
    </div>

    <!-- Select -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('car'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formSelectTwb($form->get('car')); ?>
            <?php echo $this->formElementTwb($form->get('car')); ?>
        </div>
    </div>

    <!-- MultiSelect -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('pets'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formSelectTwb($form->get('pets')); ?>
            <?php echo $this->formElementTwb($form->get('pets')); ?>
        </div>
    </div>

    <!-- File -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('attachment'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('attachment')); ?>
            <?php echo $this->formElementTwb($form->get('attachment')); ?>
        </div>
    </div>

    <!-- Text with append / prepend -->
    <div class="control-group">
        <?php echo $this->formLabelMainTwb($form->get('salary'), null, null, $formType); ?>
        <div class="controls">
            <?php //echo $this->formInputTwb($form->get('salary')); ?>
            <?php echo $this->formElementTwb($form->get('salary')); ?>
        </div>
    </div>

    <!-- CSRF -->
    <?php //TODO - display CSRF errors ?>
    <?php echo $this->formElementTwb($form->get('csrf')); ?>

    <!-- Form actions -->
    <div class="form-actions">
        <?php //echo $this->formInputTwb($form->get('submitBtn')); ?>
        <?php echo $this->formElementTwb($form->get('submitBtn')); ?>
        <?php //echo $this->formInputTwb($form->get('resetBtn')); ?>
        <?php echo $this->formElementTwb($form->get('resetBtn')); ?>
        <?php //echo $this->formInputTwb($form->get('plainBtn')); ?>
        <?php echo $this->formElementTwb($form->get('plainBtn')); ?>
    </div>
</fieldset>
<?php echo $this->form()->closeTag($form); ?>