<div class="page-header">
    <h1>Search Form</h1>
</div>
<?php
$formDisplayConfig  = array(
    'text'      => array(
        'sizeClass'     => 'span3',
    ),
);
$formType   = \DluTwBootstrap\Form\Util::FORM_TYPE_SEARCH;
$form = $this->form;
/* @var $form \DluTwBootstrap\Demo\Form\InlineForm */
$form->prepare();
//$form->setAttribute('action', $this->url('form'));
?>

<?php echo $this->formTwb($form, $formType, $formDisplayConfig); ?>