<h2>Forms</h2>
<p><i>You may find other useful information in my <a href="http://www.zfdaily.com">ZF Daily</a> blog post
    <a href="http://www.zfdaily.com/2012/04/twitter-bootstrap-forms-with-zf2-easily">Twitter Bootstrap Forms with ZF2. Easily.</a>
</i></p>
<ul>
    <li><a href="#horizontal-form-demo">Horizontal Form Demo</a></li>
    <li><a href="#vertical-form-demo">Vertical Form Demo</a></li>
    <li><a href="#inline-form-demo">Inline Form Demo</a></li>
    <li><a href="#search-form-demo">Search Form Demo</a></li>
</ul>
<?php
echo $formHorizontal;
echo $formVertical;
echo $formInline;
echo $formSearch;
?>