<div class="page-header">
    <h1>Navbar (static)</h1>
</div>

<p><i>You may find other useful information in my <a href="http://www.zfdaily.com">ZF Daily</a> blog post
    <a href="http://www.zfdaily.com">Write the blog post, ok?</a>
</i></p>
<ul>
    <li><a href="#navbar-static-demo">Navbar (static)</a></li>
    <li><a href="#navlist-demo">Nav list</a></li>
    <li><a href="#navlist-icon-demo">Nav list with icons</a></li>
</ul>
<?php

?>