<?php
//Set up the brand link
$brandLink  = new \Zend\Navigation\Page\Mvc();
$brandLink->setController('tw-bootstrap-demo');
$brandLink->setAction('index');
$brandLink->setLabel('DluTwBootstrap');
echo $this->navigation()->twbNavbar()->renderNavbar($navMenuMain, null, null,
                                                       $brandLink, null, true, false, true, true);
?>
<div class="page-header">
    <h1>Nav List</h1>
</div>
<div class="row">
    <div class="span3">
        <?php echo $this->navigation()->twbNavList()->renderNavList($navList, true, true); ?>
    </div>
    <div class="span9">
        <h4>Nav List</h4>
        <p>With optional icons and dropdowns</p>
    </div>
</div>