<?php
//echo $this->navigation()->menu($navMenuMain);
echo $this->navigation()->twbNavbar($navMenuMain);
?>

<h2>Navigation</h2>
<p><i>You may find other useful information in my <a href="http://www.zfdaily.com">ZF Daily</a> blog post
    <a href="http://www.zfdaily.com/2012/04/twitter-bootstrap-forms-with-zf2-easily">Twitter Bootstrap Forms with ZF2. Easily.</a>
</i></p>
<ul>
    <li><a href="#navbar-demo">Navbar</a></li>
</ul>
<?php

?>