<?php
/**
 * View Layout referencing all necessary Twitter Bootstrap and jQuery dependencies
 * @package DluTwBootstrap
 * @copyright David Lukas (c) - http://www.zfdaily.com
 * @license http://www.zfdaily.com/code/license New BSD License
 * @link http://www.zfdaily.com
 * @link https://bitbucket.org/dlu/dlutwbootstrap
 */

$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css');
//Twitter Bootstrap style override by DluTwBootstrap
$this->headLink()->appendStylesheet($basePath . '/css/dlu-tw-bootstrap.css');
//Add your own style here
//$this->headLink()->appendStylesheet($basePath . '/css/style.css');
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

//jQuery and Twitter Bootstrap JS libraries
$this->inlineScript()->appendFile($basePath . '/js/jquery-1.7.1.min.js');
$this->inlineScript()->appendFile($basePath . '/js/bootstrap.min.js');

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('DluTwBootstrap') ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>
    <!-- Scripts -->
    <?php echo $this->headScript() ?>
  </head>

  <body>
    <div class="container">
      <h1>DluTwBootstrap Demo</h1>
      <p>Git repository: <a href="https://bitbucket.org/dlu/dlutwbootstrap">https://bitbucket.org/dlu/dlutwbootstrap</a>
      <br />Blog: <a href="http://www.zfdaily.com">ZF Daily (www.zfdaily.com)</a></p>
      <hr />
      <?php echo $this->content; ?>
      <hr>
      <footer>
        <p>&copy; 2012 by David Lukas @ ZF Daily (<a href="http://www.zfdaily.com">www.zfdaily.com</a>). All rights reserved.</p>
      </footer>
    </div> <!-- /container -->
    <?php echo $this->inlineScript(); ?>
  </body>
</html>
