<?php
/**
 * View Layout for DluTwBootstrap Demo
 * @package DluTwBootstrap
 * @copyright David Lukas (c) - http://www.zfdaily.com
 * @license http://www.zfdaily.com/code/license New BSD License
 * @link http://www.zfdaily.com
 * @link https://bitbucket.org/dlu/dlutwbootstrap
 */

$this->headTitle()->setSeparator(' - ')
                  ->setAutoEscape(false);
$basePath = $this->basePath();

//Twitter Bootstrap styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap.min.css');
//Twitter Bootstrap style override by DluTwBootstrap
$this->headLink()->appendStylesheet($basePath . '/css/dlu-tw-bootstrap.css');
//Twitter Bootstrap responsive styles
$this->headLink()->appendStylesheet($basePath . '/css/bootstrap-responsive.min.css');

//jQuery and Twitter Bootstrap JS libraries
$this->inlineScript()->appendFile($basePath . '/js/jquery-1.7.2.min.js');
$this->inlineScript()->appendFile($basePath . '/js/bootstrap.min.js');

echo $this->doctype();
?>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('DluTwBootstrap') ?>
    <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>
    <!-- Le styles -->
    <?php echo $this->headLink() ?>
    <?php echo $this->headStyle(); ?>
    <!-- Scripts -->
    <?php echo $this->headScript() ?>
  </head>

  <body style="padding-top: 60px; padding-bottom: 40px;">
    <div class="container">
        <!-- NavBar -->
        <?php
            //Set up the brand link
            $brandLink  = new \Zend\Navigation\Page\Mvc();
            $brandLink->setController('tw-bootstrap-demo');
            $brandLink->setAction('index');
            $brandLink->setLabel('DluTwBootstrap');
            echo $this->navigation()->twbNavbar()->renderNavbar($this->navbar, null, null,
                                                                $brandLink, null, true, false, true, true);

        ?>
        <!-- /NavBar -->
        <?php echo $this->content; ?>
        <hr>
        <footer>
        <p>&copy; 2012 by David Lukas @ ZF Daily (<a href="http://www.zfdaily.com">www.zfdaily.com</a>). All rights reserved.</p>
      </footer>
    </div> <!-- /container -->
    <?php echo $this->inlineScript(); ?>
  </body>
</html>
