<div class="page-header" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html">
    <h1>Buttons</h1>
</div>
<div class="row">
    <div class="span2">
        <h4>Single Horizontal</h4>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'singleHorizontal', true); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>Single Horizontal</h4>
        <p>Without icons</p>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'singleHorizontal', false); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>Single Vertical</h4>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'singleVertical', true); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>Single Vertical</h4>
        <p>Without icons</p>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'singleVertical', false); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>Groups Horizontal</h4>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'groupsHorizontal', true); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>Groups Horizontal</h4>
        <p>Without icons</p>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'groupsHorizontal', false); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>Groups Vertical</h4>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'groupsVertical', true); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>Groups Vertical</h4>
        <p>Without icons</p>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'groupsVertical', false); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>One Group</h4>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'oneGroup', true); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
<hr>
<div class="row">
    <div class="span2">
        <h4>One Group</h4>
        <p>Without icons</p>
    </div>
    <div class="span6">
        <?php echo $this->navigation()->twbButtons()->renderButtons($this->nav, 'oneGroup', false); ?>
    </div>
    <div class="span4">
        <h5>Navigation helper call</h5>
    </div>
</div>
